anno_pubblicazione = "Anno di pubblicazione"

libri_hardcodati = [
    {
        "titolo": "Il Signore degli Anelli",
        "autore": "J.R.R. Tolkien",
        "genere": "Fantasy",
        anno_pubblicazione: "1954",
        "ISBN": "9780261103573",
        "copie": "5",
    },
    {
        "titolo": "1984",
        "autore": "George Orwell",
        "genere": "Distopia",
        anno_pubblicazione: "1949",
        "ISBN": "9780451524935",
        "copie": "3",
    },
    {
        "titolo": "Il Piccolo Principe",
        "autore": "Antoine de Saint-Exupéry",
        "genere": "Fiaba",
        anno_pubblicazione: "1943",
        "ISBN": "9780156012195",
        "copie": "7",
    },
    {
        "titolo": "Harry Potter e la Pietra Filosofale",
        "autore": "J.K. Rowling",
        "genere": "Fantasy",
        anno_pubblicazione: "1997",
        "ISBN": "9780747532699",
        "copie": "10",
    },
    {
        "titolo": "Il Codice da Vinci",
        "autore": "Dan Brown",
        "genere": "Thriller",
        anno_pubblicazione: "2003",
        "ISBN": "9780385504201",
        "copie": "4",
    },
    {
        "titolo": "Orgoglio e Pregiudizio",
        "autore": "Jane Austen",
        "genere": "Romantico",
        anno_pubblicazione: "1813",
        "ISBN": "9780141439518",
        "copie": "8",
    },
    {
        "titolo": "Moby Dick",
        "autore": "Herman Melville",
        "genere": "Avventura",
        anno_pubblicazione: "1851",
        "ISBN": "9781503280786",
        "copie": "4",
    },
    {
        "titolo": "Il Grande Gatsby",
        "autore": "F. Scott Fitzgerald",
        "genere": "Classico",
        anno_pubblicazione: "1925",
        "ISBN": "9780743273565",
        "copie": "9",
    },
    {
        "titolo": "Cime tempestose",
        "autore": "Emily Brontë",
        "genere": "Romanzo",
        anno_pubblicazione: "1847",
        "ISBN": "9781853260014",
        "copie": "2",
    },
    {
        "titolo": "La Metamorfosi",
        "autore": "Franz Kafka",
        "genere": "Letteratura",
        anno_pubblicazione: "1915",
        "ISBN": "9780141187112",
        "copie": "5",
    },
    {
        "titolo": "Le Miserabili",
        "autore": "Victor Hugo",
        "genere": "Romanzo Storico",
        anno_pubblicazione: "1862",
        "ISBN": "9780451419439",
        "copie": "3",
    },
    {
        "titolo": "Don Chisciotte della Mancia",
        "autore": "Miguel de Cervantes",
        "genere": "Avventura",
        anno_pubblicazione: "1605",
        "ISBN": "9788491050484",
        "copie": "4",
    },
    {
        "titolo": "Il Nome della Rosa",
        "autore": "Umberto Eco",
        "genere": "Giallo",
        anno_pubblicazione: "1980",
        "ISBN": "9788845241964",
        "copie": "6",
    },
    {
        "titolo": "La Divina Commedia",
        "autore": "Dante Alighieri",
        "genere": "Poetico",
        anno_pubblicazione: "1320",
        "ISBN": "9788804567982",
        "copie": "3",
    },
    {
        "titolo": "La Casa degli Spiriti",
        "autore": "Isabel Allende",
        "genere": "Romanzo",
        anno_pubblicazione: "1982",
        "ISBN": "9788478882303",
        "copie": "7",
    },
    {
        "titolo": "I Promessi Sposi",
        "autore": "Alessandro Manzoni",
        "genere": "Romanzo Storico",
        anno_pubblicazione: "1827",
        "ISBN": "9788804593806",
        "copie": "5",
    },
    {
        "titolo": "Frankenstein",
        "autore": "Mary Shelley",
        "genere": "Horror",
        anno_pubblicazione: "1818",
        "ISBN": "9780451532243",
        "copie": "4",
    },
    {
        "titolo": "Ulisse",
        "autore": "James Joyce",
        "genere": "Modernismo",
        anno_pubblicazione: "1922",
        "ISBN": "9780141182803",
        "copie": "3",
    },
    {
        "titolo": "Il Buio oltre la Siepe",
        "autore": "Harper Lee",
        "genere": "Romanzo",
        anno_pubblicazione: "1960",
        "ISBN": "9780446310789",
        "copie": "8",
    },
    {
        "titolo": "Lo Hobbit",
        "autore": "J.R.R. Tolkien",
        "genere": "Fantasy",
        anno_pubblicazione: "1937",
        "ISBN": "9780261102217",
        "copie": "10",
    },
    {
        "titolo": "Siddhartha",
        "autore": "Hermann Hesse",
        "genere": "Spiritualità",
        anno_pubblicazione: "1922",
        "ISBN": "9780142437186",
        "copie": "5",
    },
]
